name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Install Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.14.2

      - name: Install packages
        run: npm ci
     
      - name: Publish application
        run: npm run publish
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
